from collections.abc import Sequence

# Alias: method `int` shadows builtin `int` in stub parsing for `ty`.
_Int = int

class BitSet:
    def set(self, pos: _Int) -> None: ...
    def clear(self, pos: _Int) -> None: ...
    def has(self, pos: _Int) -> bool: ...
    def ior(self, other: BitSet) -> BitSet: ...
    def int(self) -> _Int: ...
    def length(self) -> _Int: ...
    def list(self) -> Sequence[_Int]: ...
